// flow-typed signature: 6f940797290fe9bf6a9c5c2d89216f70
// flow-typed version: <<STUB>>/obj-properties_v^0.2.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'obj-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'obj-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'obj-properties/lib/app' {
  declare module.exports: any;
}

declare module 'obj-properties/lib/index' {
  declare module.exports: any;
}

declare module 'obj-properties/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'obj-properties/lib/app.js' {
  declare module.exports: $Exports<'obj-properties/lib/app'>;
}
declare module 'obj-properties/lib/index.js' {
  declare module.exports: $Exports<'obj-properties/lib/index'>;
}
declare module 'obj-properties/test/test.js' {
  declare module.exports: $Exports<'obj-properties/test/test'>;
}
